# Generated by Django 3.0.4 on 2020-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
